# docker compose versions
version: '2'

# shared volumes
volumes:
  project:

services:

  # mongodb
  mongo:
    image: mongo

  # web app bundle build
  app:
    build:
      context: ./app
      args:
        branch: "${CRN_BRANCH}"
    volumes:
      - project:/srv/crn-app/dist
    env_file: ./config.env

  # crn core (bids-core)
  core:
    build: ./core
    volumes:
      - /srv/bids-core/persistent/data:${BIDS_CORE_PERSISTENT_DIR}
    env_file: ./config.env
    restart: always

  # crn node server
  server:
    build:
      context: ./server
      args:
        branch: "${CRN_BRANCH}"
    volumes:
      - /srv/bids-core/persistent/data:${BIDS_CORE_PERSISTENT_DIR}
      - /srv/crn-server/persistent:${CRN_SERVER_PERSISTENT_DIR}
    env_file: ./config.env
    restart: always

  # nginx - static file serving and service proxy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - project:/srv/crn-app/dist
    ports:
      - "80:80"
      - "443:443"