# docker compose versions
version: '2'

# shared volumes
volumes:
  project:

services:

  # mongodb
  mongo:
    image: mongo

  # web app bundle build
  app:
    image: poldracklab/crn_app:${CRN_APP_TAG}
    volumes:
      - project:/srv/crn-app/dist
    env_file: ./config.env

  # crn core (bids-core)
  core:
    build: ./core
    volumes:
      - ${BIDS_CORE_PERSISTENT_DIR}:/srv/bids-core/persistent/data
    env_file: ./config.env
    restart: always

  # crn node server
  server:
    image: poldracklab/crn_server:${CRN_SERVER_TAG}
    volumes:
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${BIDS_CORE_PERSISTENT_DIR}:/srv/bids-core/persistent/data
      - ${CRN_SERVER_PERSISTENT_DIR}:/srv/crn-server/persistent
    env_file: ./config.env
    restart: always

  # nginx - static file serving and service proxy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - project:/srv/crn-app/dist
    ports:
      - "80:80"
      - "443:443"
