# docker compose versions
version: '2'

# shared volumes
volumes:
  project:

services:

  # mongodb
  mongo:
    image: mongo

  # web app bundle build
  app:
    build:
      context: ./app
      args:
        branch: "dev"
    volumes:
      - project:/srv/crn-app/dist
    env_file: ./config.env

  # crn core (bids-core)
  core:
    build: ./core
    volumes:
      - /srv/bids-core/persistent/data:/srv/bids-core/persistent/data
    env_file: ./config.env
    restart: always

  # crn node server
  server:
    build:
      context: ./server
      args:
        branch: "dev"
    volumes:
      - /srv/bids-core/persistent/data:/srv/bids-core/persistent/data
      - /srv/crn-server/persistent:/srv/crn-server/persistent
    env_file: ./config.env
    restart: always

  # nginx - static file serving and service proxy
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - project:/srv/crn-app/dist
    ports:
      - "80:80"
      - "443:443"
